### ISSUE TITLE
Question: Can this be used to notify when an entry is expired (or about to be)?

### ISSUE THREAD

**Issue by swthate** [Rias500/craft-notifications#5]
Can this be used to notify a certain group of users when an entry is about to expire?

**Comment by Rias500** [comment]
It can for the notification part, but you'd have to trigger an event manually that the notification plugin can listen to because there is no built in Craft event that allows for this.

Basic steps that you'll have to do to implement this:
- Create a console command that checks all the entries that are about to expire
- Fire an event (either for each entry or for the collection of entries)
- Attach a notification to this event
- Run the console command in a cronjob that checks every so often
