### ISSUE TITLE
FR: Execute/command function

### ISSUE THREAD

**Issue by theskyfloor** [Rias500/craft-notifications#8]
This falls outside of the "notifications" purpose of this plug-in but I see this plug-in as potentially having even more power around events in general. Why not make it so the plug-in gives us a way to manipulate data via our classes based on Craft events? To that end, I would love it if there was an execute or command method that fired every time the notification class is triggered. Using this method I could do something like check the value of a field and change the content/properties of an element (user, entry, etc). Thoughts?

I tried adding this myself to no avail, I also tried manipulating data in some of the existing methods but it seems like it just gets ignored. Perhaps the context of these classes isn't appropriate for executing custom code like what I am suggesting but if it is - this would be a rad extension of the events construct you have created! Thanks!

**Comment by theskyfloor** [comment]
Hey, @Rias500 have you had a chance to consider this? Thanks!

**Comment by Rias500** [comment]
@theskyfloor Sorry for the long wait time on my reply, but this is not something I'll add to this plugin. Adding to that, most of what you want to do here is easily achieved by writing a small custom module in your project and listening for events in there, this makes a lot more sense too because it's probably tied to business logic of your project. 

The only advantage to a plugin like this would be that you can add your listeners from a config file and trigger classes or jobs from it. If you need a plugin like that, it's not very complicated, but I probably won't make or maintain it on my own time.

**Comment by theskyfloor** [comment]
Thanks for your consideration!
